# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = subdirs
SUBDIRS += RequestFlow/RequestFlow.pro \
    CoreModel/CoreModel.pro \
    CoreView/CoreView.pro
DEPENDPATH += CoreModel/
DEPENDPATH += CoreView/
