# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = BleachUI
DESTDIR = ../x64/Release
CONFIG += release console
LIBS += -L"." \
    -lBleachUIModel
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(BleachUI.pri)
