#ifndef EXECUTIONENGINE_GLOBAL_H
#define EXECUTIONENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXECUTIONENGINE_LIBRARY)
#  define EXECUTIONENGINE_EXPORT Q_DECL_EXPORT
#else
#  define EXECUTIONENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // EXECUTIONENGINE_GLOBAL_H
