# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = BleachUIModel
DESTDIR = ../x64/Release
CONFIG += release
DEFINES += BLEACHUIMODEL_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(BleachUIModel.pri)
