# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = subdirs
SUBDIRS += RequestFlow/RequestFlow.pro \
    CoreModel/CoreModel.pro \
    CoreView/CoreView.pro \
    ExecutionEngine
DEPENDPATH += CoreModel/
DEPENDPATH += CoreView/
DEPENDPATH += ExecutionEngine/
