# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS += CoreModel/CoreModel.pro \
    CoreView/CoreView.pro \
    ExecutionEngine/ExecutionEngine.pro \
    RequestFlow/RequestFlow.pro
