# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core webchannel websockets xml xmlpatterns
TEMPLATE = lib
TARGET = CoreModel
CONFIG += c++11
DEFINES += COREMODEL_LIB

include(CoreModel.pri)
